import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface AuctionResultPDFData {
  auctionCode: string;
  securityName: string;
  securityType: string;
  auctionDate: string;
  settlementDate: string;
  targetAmount: number;
  totalBids: number;
  totalAccepted: number;
  bidCoverRatio: number;
  highRate?: number;
  lowRate?: number;
  weightedAverageRate: number;
  marginalRate?: number;
  price: number;
  status: string;
  tenor: string;
  cusip: string;
}

interface TradeConfirmationPDFData {
  orderId: string;
  securityName: string;
  type: 'BUY' | 'SELL';
  orderType: 'MARKET' | 'LIMIT';
  quantity: number;
  price?: number;
  averagePrice?: number;
  totalValue: number;
  commission: number;
  fees: number;
  netValue: number;
  status: string;
  createdAt: string;
  filledAt?: string;
}

export class PDFGenerator {
  private static addHeader(doc: jsPDF, title: string) {
    // Add Constant Treasury branding
    doc.setFillColor(25, 95, 53); // Primary color
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Constant Treasury', 20, 25);
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Ghana\'s Premier Digital Trading Platform', 20, 35);
    
    // Add title
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 20, 55);
  }

  private static addFooter(doc: jsPDF) {
    const pageCount = doc.getNumberOfPages();
    const page = pageCount;
    
    doc.setFillColor(240, 240, 240);
    doc.rect(0, 270, 210, 30, 'F');
    
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Page ${page} of ${pageCount}`, 105, 280, { align: 'center' });
    doc.text('Generated by Constant Treasury - constantcap.com.gh', 105, 290, { align: 'center' });
    doc.text(`Generated on ${new Date().toLocaleDateString('en-GH')}`, 105, 295, { align: 'center' });
  }

  static generateAuctionResultPDF(data: AuctionResultPDFData): jsPDF {
    const doc = new jsPDF();
    
    // Add header
    this.addHeader(doc, 'Auction Results Report');
    
    // Auction details
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Auction Details', 20, 75);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const details = [
      `Auction Code: ${data.auctionCode}`,
      `Security: ${data.securityName}`,
      `Type: ${data.securityType.replace('_', ' ')}`,
      `Tenor: ${data.tenor}`,
      `CUSIP: ${data.cusip}`,
      `Auction Date: ${new Date(data.auctionDate).toLocaleDateString('en-GH')}`,
      `Settlement Date: ${new Date(data.settlementDate).toLocaleDateString('en-GH')}`,
      `Status: ${data.status.replace('_', ' ')}`
    ];
    
    details.forEach((detail, index) => {
      doc.text(detail, 20, 85 + (index * 6));
    });
    
    // Financial details
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Financial Results', 20, 145);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const financials = [
      `Target Amount: GHS ${data.targetAmount.toLocaleString()}`,
      `Total Bids: GHS ${data.totalBids.toLocaleString()}`,
      `Total Accepted: GHS ${data.totalAccepted.toLocaleString()}`,
      `Bid Cover Ratio: ${data.bidCoverRatio.toFixed(2)}x`,
      `Weighted Average Rate: ${data.weightedAverageRate.toFixed(2)}%`,
      `Price: ${data.price.toFixed(2)}`
    ];
    
    if (data.highRate && data.lowRate) {
      financials.push(`High Rate: ${data.highRate.toFixed(2)}%`);
      financials.push(`Low Rate: ${data.lowRate.toFixed(2)}%`);
    }
    if (data.marginalRate) {
      financials.push(`Marginal Rate: ${data.marginalRate.toFixed(2)}%`);
    }
    
    financials.forEach((financial, index) => {
      doc.text(financial, 20, 155 + (index * 6));
    });
    
    // Add performance chart (simple bar chart representation)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Subscription Performance', 20, 210);
    
    // Simple bar chart
    const chartX = 20;
    const chartY = 220;
    const chartWidth = 170;
    const chartHeight = 40;
    
    // Draw chart background
    doc.setDrawColor(200, 200, 200);
    doc.rect(chartX, chartY, chartWidth, chartHeight);
    
    // Draw subscription bar
    const subscriptionPercent = Math.min((data.totalBids / data.targetAmount) * 100, 200);
    const barWidth = (subscriptionPercent / 200) * chartWidth;
    
    doc.setFillColor(25, 95, 53);
    doc.rect(chartX, chartY, barWidth, chartHeight, 'F');
    
    // Add labels
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text('0%', chartX, chartY + chartHeight + 5);
    doc.text('100%', chartX + chartWidth/2, chartY + chartHeight + 5);
    doc.text('200%', chartX + chartWidth, chartY + chartHeight + 5);
    doc.text(`Subscription: ${subscriptionPercent.toFixed(1)}%`, chartX + chartWidth/2, chartY - 5, { align: 'center' });
    
    // Add footer
    this.addFooter(doc);
    
    return doc;
  }

  static generateTradeConfirmationPDF(data: TradeConfirmationPDFData): jsPDF {
    const doc = new jsPDF();
    
    // Add header
    this.addHeader(doc, 'Trade Confirmation');
    
    // Order details
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Order Details', 20, 75);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const orderDetails = [
      `Order ID: ${data.orderId}`,
      `Security: ${data.securityName}`,
      `Order Type: ${data.type} - ${data.orderType}`,
      `Status: ${data.status.replace('_', ' ')}`,
      `Created: ${new Date(data.createdAt).toLocaleDateString('en-GH', { 
        year: 'numeric', 
        month: 'short', 
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })}`
    ];
    
    if (data.filledAt) {
      orderDetails.push(`Filled: ${new Date(data.filledAt).toLocaleDateString('en-GH', { 
        year: 'numeric', 
        month: 'short', 
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })}`);
    }
    
    orderDetails.forEach((detail, index) => {
      doc.text(detail, 20, 85 + (index * 6));
    });
    
    // Execution details
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Execution Details', 20, 135);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const executionDetails = [
      `Quantity: ${data.quantity.toLocaleString()}`,
      `Price: ${data.price ? data.price.toFixed(2) : 'Market'}`,
      `Average Price: ${data.averagePrice ? data.averagePrice.toFixed(2) : 'N/A'}`,
      `Total Value: GHS ${data.totalValue.toLocaleString()}`,
      `Commission: GHS ${data.commission.toLocaleString()}`,
      `Fees: GHS ${data.fees.toLocaleString()}`,
      `Net Value: GHS ${data.netValue.toLocaleString()}`
    ];
    
    executionDetails.forEach((detail, index) => {
      doc.text(detail, 20, 145 + (index * 6));
    });
    
    // Add summary box
    doc.setFillColor(245, 245, 245);
    doc.rect(20, 200, 170, 30, 'F');
    doc.setDrawColor(200, 200, 200);
    doc.rect(20, 200, 170, 30);
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Transaction Summary', 30, 215);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`Net Amount: GHS ${data.netValue.toLocaleString()}`, 30, 225);
    
    // Add footer
    this.addFooter(doc);
    
    return doc;
  }

  static generatePortfolioStatementPDF(
    positions: any[],
    summary: any,
    showBalance: boolean = true
  ): jsPDF {
    const doc = new jsPDF();
    
    // Add header
    this.addHeader(doc, 'Portfolio Statement');
    
    // Portfolio summary
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Portfolio Summary', 20, 75);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const summaryDetails = [
      `Total Portfolio Value: ${showBalance ? `GHS ${summary.totalValue.toLocaleString()}` : '••••••'}`,
      `Total Cost: ${showBalance ? `GHS ${summary.totalCost.toLocaleString()}` : '••••••'}`,
      `Total P&L: ${showBalance ? `GHS ${summary.totalPnL.toLocaleString()} (${summary.totalPnLPercent.toFixed(2)}%)` : '••••••'}`,
      `Available to Trade: ${showBalance ? `GHS ${summary.availableToTrade.toLocaleString()}` : '••••••'}`,
      `Average Yield: ${summary.totalYield.toFixed(2)}%`,
      `Day Change: ${showBalance ? `GHS ${summary.dayChange.toLocaleString()} (${summary.dayChangePercent.toFixed(2)}%)` : '••••••'}`
    ];
    
    summaryDetails.forEach((detail, index) => {
      doc.text(detail, 20, 85 + (index * 6));
    });
    
    // Holdings table
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Current Holdings', 20, 135);
    
    // Create table headers
    const headers = [['Security', 'Quantity', 'Avg Price', 'Current Price', 'Market Value', 'P&L']];
    const data = positions.map(position => [
      position.securityName,
      position.quantity.toLocaleString(),
      position.averagePrice.toFixed(2),
      position.currentPrice.toFixed(2),
      showBalance ? `GHS ${position.marketValue.toLocaleString()}` : '••••••',
      showBalance ? `GHS ${position.unrealizedPnL.toLocaleString()} (${position.unrealizedPnLPercent.toFixed(2)}%)` : '••••••'
    ]);
    
    // Add table using autoTable
    autoTable(doc, {
      head: headers,
      body: data,
      startY: 145,
      theme: 'grid',
      styles: {
        fontSize: 8,
        cellPadding: 2,
      },
      headStyles: {
        fillColor: [25, 95, 53],
        textColor: 255,
        fontStyle: 'bold'
      },
      alternateRowStyles: {
        fillColor: [245, 245, 245]
      }
    });
    
    // Add footer
    this.addFooter(doc);
    
    return doc;
  }
}

export default PDFGenerator;
